name: Deploy to GitHub Pages

on:
s  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Replace Supabase Anon Key Placeholder
      run: |
        sed -i "s|__SUPAKEY__|${{ secrets.SUPABASE_ANON_KEY }}|g" main.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./